### ISSUE TITLE
When can we use dmclock in Ceph?

### ISSUE THREAD

**Issue by scienceluo** [ceph/dmclock#11]
It seems that dmclock is very cool to Cephers, but when can we use dmclock in Ceph?
@ivancich

**Comment by ivancich** [comment]
We have it working in certain ceph branches and we're currently evaluating it in terms of performance and flexibility of configuration. We're also working on and evaluating enhancements to it working with some researchers at UC Santa Cruz.

We're happy that you're interested?

Just so we can better understand interest and demand, what do you hope to get from the integration of dmclock in Ceph?

Thanks!

**Comment by scienceluo** [comment]
If possible，we also wanna get the branch to test in our lab.
And feedback as soon as possible so that we can fix them together ^_^

**Comment by ivancich** [comment]
Here's the branch:
https://github.com/ceph/ceph/tree/wip_dmclock2

**Comment by scienceluo** [comment]
So this wip_dmclock2 branch based on the latest master branch or another branch?

**Comment by ivancich** [comment]
It is based on master and gets re-based approximately once per week.
