### ISSUE TITLE
confused error while compiling "dmclock-tests"

### ISSUE THREAD

**Issue by Yan-waller** [ceph/dmclock#17]
@ivancich Hi sir, I'm interested in `dmclock` and tried to use it. 
```
[root@tana75 dmclock]# cmake . -DCMAKE_BUILD_TYPE=Debug -DPROFILE=yes -DDO_NOT_DELAY_TAG_CALC=yes
-- Boost version: 1.53.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yanjun/git/dmclock
[root@tana75 dmclock]# make
[ 33%] Building CXX object src/CMakeFiles/dmclock.dir/dmclock_util.cc.o
[ 66%] Building CXX object src/CMakeFiles/dmclock.dir/__/support/src/run_every.cc.o
Linking CXX static library libdmclock.a
[ 66%] Built target dmclock
[100%] Building CXX object support/test/CMakeFiles/test_intru_heap.dir/test_intrusive_heap.cc.o
Linking CXX executable test_intru_heap
[100%] Built target test_intru_heap
[root@tana75 dmclock]# 
```
But I encountered problems when I tried to compile the `dmclock-tests` or `dmclock-sims` targets as following:
```
[root@tana75 dmclock]# make dmclock-tests
Linking CXX executable ../../test/data-struct-tests
/usr/bin/ld: cannot find -lPUBLIC
collect2: error: ld returned 1 exit status
make[3]: *** [test/data-struct-tests] Error 1
make[2]: *** [support/test/CMakeFiles/data-struct-tests.dir/all] Error 2
make[1]: *** [test/CMakeFiles/dmclock-tests.dir/rule] Error 2
make: *** [dmclock-tests] Error 2
[root@tana75 dmclock]# 
```
It sounds that `PUBLIC` is not a normal library, why shoud we link to this?  Is there anything I missed?

**Comment by ivancich** [comment]
Please check the version of cmake you have. It appears as though the PUBLIC directive in cmake's target_link_libraries is being interpreted as a literal library. See: https://cmake.org/cmake/help/v3.0/command/target_link_libraries.html

It builds using cmake 3.4.3 for me and the PUBLIC directive appears to go back to version 3.0 of cmake if not earlier.

~ $ mkdir dmclock-test
~ $ cd dmclock-test
~/dmclock-test $ git clone git@github.com:ceph/dmclock.git
Cloning into 'dmclock'...
remote: Counting objects: 3052, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 3052 (delta 24), reused 2 (delta 2), pack-reused 2996
Receiving objects: 100% (3052/3052), 888.44 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2188/2188), done.
Checking connectivity... done.
~/dmclock-test $ cd dmclock
~/dmclock-test/dmclock (master)$ mkdir build
~/dmclock-test/dmclock (master)$ cd build
~/dmclock-test/dmclock/build (master)$ cmake --version
cmake version 3.4.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
~/dmclock-test/dmclock/build (master)$ cmake ..
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- build type '' is neither 'Release' nor 'Debug'; assuming Debug
-- Found gtest: /usr/lib64/libgtest.so  
-- Could NOT find gmock (missing:  GMOCK_LIBRARY GMOCK_MAIN_LIBRARY GMOCK_INCLUDE_DIRS) 
-- Boost version: 1.58.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home2/ivancich/dmclock-test/dmclock/build
~/dmclock-test/dmclock/build (master)$ make dmclock-tests
Scanning dependencies of target data-struct-tests
[ 10%] Building CXX object support/test/CMakeFiles/data-struct-tests.dir/test_indirect_intrusive_heap.cc.o
[ 20%] Linking CXX executable ../../test/data-struct-tests
[ 20%] Built target data-struct-tests
Scanning dependencies of target dmclock
[ 30%] Building CXX object src/CMakeFiles/dmclock.dir/dmclock_util.cc.o
[ 40%] Building CXX object src/CMakeFiles/dmclock.dir/__/support/src/run_every.cc.o
[ 50%] Linking CXX static library libdmclock.a
[ 50%] Built target dmclock
Scanning dependencies of target dmclock-tests
[ 60%] Building CXX object test/CMakeFiles/dmclock-tests.dir/test_test_client.cc.o
[ 70%] Building CXX object test/CMakeFiles/dmclock-tests.dir/test_dmclock_server.cc.o
[ 80%] Building CXX object test/CMakeFiles/dmclock-tests.dir/test_dmclock_client.cc.o
[ 90%] Building CXX object test/CMakeFiles/dmclock-tests.dir/__/sim/src/test_dmclock.cc.o
[100%] Linking CXX executable dmclock-tests
[100%] Built target dmclock-tests
~/dmclock-test/dmclock/build (master)$ make dmclock-sims
[ 25%] Built target dmclock
Scanning dependencies of target dmc_sim
[ 33%] Building CXX object sim/src/CMakeFiles/dmc_sim.dir/test_dmclock.cc.o
[ 41%] Building CXX object sim/src/CMakeFiles/dmc_sim.dir/test_dmclock_main.cc.o
[ 50%] Building CXX object sim/src/CMakeFiles/dmc_sim.dir/config.cc.o
[ 58%] Building CXX object sim/src/CMakeFiles/dmc_sim.dir/str_list.cc.o
[ 66%] Building CXX object sim/src/CMakeFiles/dmc_sim.dir/ConfUtils.cc.o
[ 75%] Linking CXX executable ../dmc_sim
[ 75%] Built target dmc_sim
Scanning dependencies of target ssched_sim
[ 83%] Building CXX object sim/src/CMakeFiles/ssched_sim.dir/test_ssched.cc.o
[ 91%] Building CXX object sim/src/CMakeFiles/ssched_sim.dir/test_ssched_main.cc.o
[100%] Linking CXX executable ../ssched_sim
[100%] Built target ssched_sim
Scanning dependencies of target dmclock-sims
[100%] Built target dmclock-sims
~/dmclock-test/dmclock/build (master)$

**Comment by Yan-waller** [comment]
@ivancich thank you, that works.

my cmake version is 2.8.11
```
[root@tana75 dmclock]# cmake --version
cmake version 2.8.11
```
and the `minimum_required` is 2.8 in the `CMakeLists.txt`, so may be we should fix this mini required version ?
```
[root@tana75 dmclock]# cat CMakeLists.txt     
cmake_minimum_required(VERSION 2.8)
```

**Comment by ivancich** [comment]
Good point! The minimum has been increased to 2.8.12 as that seems to be the introduction of the PUBLIC option to target_link_libraries. Thank you!
