### ISSUE TITLE
where is gtest/gtest_prod.h

### ISSUE THREAD

**Issue by ZhenyuLeng** [ceph/dmclock#18]
Hi, i'm so interesting in dmclock.
I was just compiling the wip_dmclock2, but i met this error:

In file included from ./common/mClockPriorityQueue.h:26:0,
                 from ./osd/mClockOpClassQueue.h:26,
                 from osd/OSD.h:52,
                 from osd/PG.cc:23:
./dmclock/src/dmclock_server.h:45:30: fatal error: gtest/gtest_prod.h: No such file or directory
 #include "gtest/gtest_prod.h"

What can be done to fix it? Thank you very much!

**Comment by ZhenyuLeng** [comment]
i fix this error. The i got another error:

In file included from ./common/mClockPriorityQueue.h:26:0,
                 from ./osd/mClockOpClassQueue.h:26,
                 from ./osd/OSD.h:52,
                 from tools/ceph_objectstore_tool.cc:35:
./dmclock/src/dmclock_server.h:36:37: fatal error: indirect_intrusive_heap.h: No such file or directory
 #include "indirect_intrusive_heap.h"

How to fix this? Thanks!

**Comment by ZhenyuLeng** [comment]
i found that a line in Makefile of ceph/src:

DMC_SUPPORT_CXXFLAGS = \                                                                                           
         -I$(top_srcdir)/src/dmclock/support

shoud be

DMC_SUPPORT_CXXFLAGS = \                                                                                           
         -I$(top_srcdir)/src/dmclock/support/src

and the problem will be solved.
Is it right?

**Comment by ivancich** [comment]
Are you using cmake? ceph is making the transition from autoconf to cmake. Much of this is documented in README.md.

**Comment by ZhenyuLeng** [comment]
I use autogen.sh configure and make

 

Best Regards,

 

Zhenyu Leng

冷镇宇

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 Eric Ivancich
发送时间: 2016年8月26日 22:34
收件人: ceph/dmclock <dmclock@noreply.github.com>
抄送: ZhenyuLeng <lengzhenyu@ict.ac.cn>; Author <author@noreply.github.com>
主题: Re: [ceph/dmclock] where is gtest/gtest_prod.h (#18)

 

Are you using cmake? ceph is making the transition from autoconf to cmake. Much of this is documented in README.md.

**Comment by ivancich** [comment]
Did using cmake resolve your issues?

**Comment by ZhenyuLeng** [comment]
Yep, thank you very much!
